// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOW0H_4jzD6tSEgSz0LHZTGSi0hM5izCk',
    appId: '1:341707481053:web:d8a173305139074d20a034',
    messagingSenderId: '341707481053',
    projectId: 'knotted-donut',
    authDomain: 'knotted-donut.firebaseapp.com',
    storageBucket: 'knotted-donut.appspot.com',
    measurementId: 'G-6MB8EKV1D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxyltwYCtgkQI0MxTLmWUGBPc-0X5wOs',
    appId: '1:341707481053:android:f8fae548d8c6ae3f20a034',
    messagingSenderId: '341707481053',
    projectId: 'knotted-donut',
    storageBucket: 'knotted-donut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa0DzRRUg78mJVZkzjn7h02SYMg-Q7dH0',
    appId: '1:341707481053:ios:f9f5130c5d538eb220a034',
    messagingSenderId: '341707481053',
    projectId: 'knotted-donut',
    storageBucket: 'knotted-donut.appspot.com',
    iosClientId: '341707481053-9sjh5a80ve2jolj77inhsd822h06bgm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKnottedTdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa0DzRRUg78mJVZkzjn7h02SYMg-Q7dH0',
    appId: '1:341707481053:ios:f9f5130c5d538eb220a034',
    messagingSenderId: '341707481053',
    projectId: 'knotted-donut',
    storageBucket: 'knotted-donut.appspot.com',
    iosClientId: '341707481053-9sjh5a80ve2jolj77inhsd822h06bgm9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterKnottedTdd',
  );
}
